UGUU(1)
=======
slowpoke <mail+git@slowpoke.io>
:encoding: utf-8
:doctype: manpage
:man source: Tinfoil Wizards Inc.
:man manual: Weeaboo Toolkit Manual

NAME
----
uguu - Generate Flexget config files.

SYNOPSIS
--------
uguu [-h] [-o] uguu_config flexget_config

DESCRIPTION
-----------
uguu is a tool to generate flexget configuration files, which aren't well suited
to some use cases, one being having a separate feed for every series, which is
important for fast moving RSS feeds such as Nyaatorrents, or simply if one likes
to download a series without batches using flexget.

CONFIGURATION
-------------
The configuration of uguu is based on series. It uses a YAML configuration file
- just like Flexget does. Every series has a RSS feed and a number of optional
  settings. These correspond to Flexget's options for series, such as
*from_group* or *quality*.  Series are mapped to a feed of the same name, which
will contain the RSS feed and a series entry with the settings, if any.

Additionally, it has a global options field, where the processing of entries is
configured. They are mapped to the special *global* preset in Flexget, which -
as the name suggests - is applied to all tasks.

Currently, uguu only supports the *download* and *deluge* output plugins, though
adding others should be fairly trivial. Take note that *download* is an implied
setting - it will automatically be turned on if *path* is set.

A sample config might look like this:

    options:
      reject:
        - .*
      accept:
        - Foobar|Baz
      path: /path/to/torrents"
      movedone: /path/to/files"
      deluge:
        label: "uguu"
        queuetotop: yes
    series:
      herp:
        rss: http://www.nyaa.eu/?page=rss
        from_group: Derpadurr
      derp:
        rss: http://www.nyaa.eu/?page=rss
        quality: 1080p
      hurr:
        rss: http://www.nyaa.eu/?page=rss
      durr:
        rss: http://www.nyaa.eu/?page=rss
